"""Run SIM-0: generate golden sample arrays, measure spectra, emit C tables."""
import json
import numpy as np
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.signal.windows import blackmanharris
import params as P
import sim0_reference as s0

MODES = {
    "lfm":   lambda w: s0.gen_lfm(P.F_LO, P.F_HI, P.N_PULSE, w),
    "geom":  lambda w: s0.gen_geom(P.F_LO, P.F_HI, P.N_PULSE, w),
    "bpsk":  lambda w: s0.gen_bpsk(200e3, P.N_PULSE, w),
}

def measure_sfdr(f_target, n=65536):
    """In-band SFDR of the integer datapath at one tone.

    Uses the REAL tuning word for f_target.  An earlier version snapped
    f_target to an exact FFT bin, which silently forced ftw = k*2^19 --
    identical single-bit phase truncation at every frequency, and therefore
    the same SFDR to 0.01 dB.  That measured the test, not the DDS.

    Accepting the real ftw means accepting spectral leakage, so the capture is
    weighted with a 4-term Blackman-Harris (-92 dB sidelobes), which sits well
    below the ~-70 dBc phase-truncation spurs we are trying to see.
    """
    w_rect = s0.make_window("rect", n)
    x, _ = s0.gen_bpsk(f_target, n, w_rect, code=np.array([1], dtype=np.int8))
    sig = (x.astype(np.float64) - 128.0) * blackmanharris(n)
    X = np.abs(np.fft.rfft(sig))
    guard = 8                                   # BH mainlobe half-width in bins
    X[:guard] = 0.0                             # kill DC
    peak = int(X.argmax())
    carrier = X[peak]
    X2 = X.copy()
    X2[max(0, peak - guard):peak + guard + 1] = 0.0
    spur_bin = int(X2.argmax())
    return (spur_bin * P.FS / n), 20 * np.log10(X2[spur_bin] / carrier)

def main():
    report = {"params": {"fs": P.FS, "bits": P.DAC_BITS, "n_pulse": P.N_PULSE},
              "sidelobes": {}, "sfdr": {}}

    # ---- 1. all modulations x all windows -----------------------------
    fig, axes = plt.subplots(3, 1, figsize=(9, 10), sharex=True)
    for ax, (mode, gen) in zip(axes, MODES.items()):
        report["sidelobes"][mode] = {}
        for wname in P.WINDOWS:
            w = s0.make_window(wname, P.N_PULSE)
            x, _ = gen(w)
            np.save(P.OUT / f"sim0_{mode}_{wname}.npy", x)
            psl = s0.peak_sidelobe_db(x)
            report["sidelobes"][mode][wname] = round(float(psl), 2)
            f, S = s0.spectrum(x)
            m = f <= 1.2e6
            ax.plot(f[m] / 1e3, S[m], lw=0.9, label=f"{wname}  PSL {psl:.0f} dB")
        ax.set_title(f"SIM-0  {mode}", loc="left", fontsize=10)
        ax.set_ylim(-100, 5); ax.grid(alpha=.3); ax.legend(fontsize=7, ncol=4)
        ax.set_ylabel("dBc")
    axes[-1].set_xlabel("frequency [kHz]")
    fig.tight_layout(); fig.savefig(P.OUT / "sim0_spectra.png", dpi=110); plt.close(fig)

    # ---- 2. quantisation spur floor -----------------------------------
    for ft in P.F_TEST:
        f_spur, sfdr = measure_sfdr(ft)
        report["sfdr"][f"{ft/1e3:.0f}kHz"] = round(float(sfdr), 2)
        report.setdefault("worst_spur_freq_kHz", {})[f"{ft/1e3:.0f}kHz"] = round(f_spur/1e3, 1)
    # SFDR values are negative dBc: the WORST case is the one closest to the
    # carrier, i.e. the maximum, not the minimum.
    report["sfdr_worst"] = round(max(report["sfdr"].values()), 2)
    report["spur_floor_target"] = P.SPUR_FLOOR_DBC
    report["spurs_in_band"] = {k: bool(P.F_LO/1e3 <= v <= P.F_HI/1e3)
                               for k, v in report["worst_spur_freq_kHz"].items()}
    report["sfdr_meets_target"] = report["sfdr_worst"] <= P.SPUR_FLOOR_DBC

    # ---- 3. ZOH droop across the band ---------------------------------
    report["zoh_droop_db"] = {f"{f/1e3:.0f}kHz": round(float(s0.zoh_sinc(np.array([f]))[0]), 3)
                              for f in P.F_TEST}

    # ---- 4. C header so firmware shares the identical tables ----------
    emit_header()

    (P.OUT / "sim0_report.json").write_text(json.dumps(report, indent=2))
    return report

def emit_header():
    lut = s0.SINE_LUT
    lines = ["/* AUTO-GENERATED by run_sim0.py -- do not edit. */",
             "#ifndef SIM0_TABLES_H", "#define SIM0_TABLES_H", "#include <stdint.h>", "",
             f"#define LUT_BITS   {P.LUT_BITS}", f"#define LUT_SIZE   {P.LUT_SIZE}",
             f"#define PHASE_BITS {P.PHASE_BITS}", f"#define N_PULSE    {P.N_PULSE}", "",
             f"static const uint8_t SINE_LUT[{P.LUT_SIZE}] = {{"]
    for i in range(0, len(lut), 16):
        lines.append("  " + ",".join(f"{v:3d}" for v in lut[i:i+16]) + ",")
    lines.append("};\n")
    for wname in P.WINDOWS:
        w = s0.make_window(wname, P.N_PULSE)
        lines.append(f"static const uint16_t WIN_{wname.upper()}_T[{P.N_PULSE}] = {{")
        for i in range(0, len(w), 16):
            lines.append("  " + ",".join(f"{v:5d}" for v in w[i:i+16]) + ",")
        lines.append("};\n")
    lines.append("#endif")
    (P.ROOT / "sim1_firmware" / "sim0_tables.h").write_text("\n".join(lines))

if __name__ == "__main__":
    r = main()
    print(json.dumps(r, indent=2))
