"""Regenerate every Sim-0 output: firmware tables, metrics, figures, and the
synthetic predicted-vs-measured pipeline test.

    .venv/bin/python sim/sim0/run_all.py            # 10 MS/s (default)
    .venv/bin/python sim/sim0/run_all.py --fs 5e6   # documented fallback rate
"""
import argparse
import json
import os
import zlib

import numpy as np
from scipy import signal

import sim0
from compare import compare
from plot import C, INK2, MUTED, band, legend_below, plt, save

HERE = os.path.dirname(os.path.abspath(__file__))


# ---- firmware tables ----------------------------------------------------------
def write_headers(reg, fs, outdir):
    d = os.path.join(outdir, "firmware")
    os.makedirs(d, exist_ok=True)
    groups = {"lfm": [], "geo": [], "barker13": [], "lfm_centres": []}
    for name in reg:
        g = "lfm_centres" if name.startswith("lfm_c") else name.rsplit("_", 1)[0]
        groups[g].append(name)
    manifest = ["name,mod,window,fs_hz,n,duration_us,params,crc32"]
    for g, names in groups.items():
        path = os.path.join(d, f"sim0_{g}.h")
        L = ["// AUTO-GENERATED by sim/sim0/run_all.py -- do not edit by hand.",
             "// Sim-0 golden-reference DAC tables for the 8-bit R-2R ladder on GPIO16-23.",
             "// code = floor(128 + 127*x + 0.5), x = modulation * window in [-1,1].",
             "// Idle (between pulses) = 128. Full scale always: amplitude is set in analog",
             "// by the MCP41010, never by scaling these codes.",
             "// Tables are const (flash/XIP); copy to an SRAM buffer before DMA streaming.",
             "#pragma once", "#include <stdint.h>", "",
             f"#ifndef SIM0_FS_HZ\n#define SIM0_FS_HZ {int(fs)}u\n#endif",
             f"#if SIM0_FS_HZ != {int(fs)}u\n#error \"sim0 tables generated for a different sample rate\"\n#endif", ""]
        for name in names:
            x, codes, meta = reg[name]
            crc = zlib.crc32(codes.tobytes())
            params = " ".join(f"{k}={v:g}" if isinstance(v, float) else f"{k}={v}"
                              for k, v in meta.items() if k not in ("window", "fs", "n", "mod"))
            N = name.upper()
            L += [f"// {name}: {params} window={meta['window']} n={len(codes)} "
                  f"({len(codes) / fs * 1e6:.1f} us)",
                  f"#define SIM0_{N}_LEN {len(codes)}u",
                  f"#define SIM0_{N}_CRC32 0x{crc:08x}u  /* zlib/IEEE CRC-32 over the bytes */",
                  f"static const uint8_t SIM0_{N}[{len(codes)}] = {{"]
            for i in range(0, len(codes), 20):
                L.append("  " + ",".join(f"{v:3d}" for v in codes[i:i + 20]) + ",")
            L += ["};", ""]
            manifest.append(f"{name},{meta['mod']},{meta['window']},{int(fs)},{len(codes)},"
                            f"{len(codes) / fs * 1e6:.1f},{params},0x{crc:08x}")
        with open(path, "w") as fh:
            fh.write("\n".join(L))
        print("  wrote", path)
    with open(os.path.join(d, "tables_manifest.csv"), "w") as fh:
        fh.write("\n".join(manifest) + "\n")


# ---- metrics ------------------------------------------------------------------
def metrics(reg, fs):
    M = {"fs_hz": fs}
    # 1. window textbook sidelobes
    M["window_psl_db"] = {w: sim0.window_psl_db(w) for w in sim0.WINDOWS}

    # 2. quantisation: SQNR per table, plus the theoretical full-scale figure
    M["sqnr_theory_fullscale_sine_db"] = 6.02 * sim0.BITS + 1.76
    M["sqnr_db"] = {k: sim0.sqnr_db(x, c) for k, (x, c, _) in reg.items()}
    # digital amplitude scaling (the rejected alternative to analog amplitude control)
    tone = np.sin(2 * np.pi * 0.0331 * np.arange(20000) + 0.3)
    M["sqnr_vs_digital_scale_db"] = {f"{s:g}": sim0.sqnr_db(s * tone, sim0.quantise(s * tone))
                                     for s in (1, 0.5, 0.25, 0.125)}

    # 3. CW FFT floor (8192-pt), the "-86 dB" claim; and the exact-ratio tones
    M["cw_8192_noncoherent"] = dict(zip(("floor_per_bin_dbc", "worst_spur_dbc"),
                                        sim0.cw_floor(331 * fs / 8192, fs, 8192)))
    M["cw_exact_ratio_tones"] = {f"{int(f / 1e3)}k": dict(zip(("floor_per_bin_dbc", "worst_spur_dbc"),
                                                              sim0.cw_floor(f, fs, 8000)))
                                 for f in sim0.CENTRES}

    # 4. tone-burst sidelobes, ideal float vs 8-bit (does 8-bit keep Blackman's -58?)
    fc, T = 300e3, sim0.PULSE_T
    tb = {}
    for w in sim0.WINDOWS:
        s = np.sin(2 * np.pi * fc * np.arange(sim0.n_samples(T, fs)) / fs) * sim0.window(w, sim0.n_samples(T, fs))
        c = sim0.quantise(s)
        pi, fi = sim0.burst_sidelobes(w, sim0.AMP * s, fs, fc, T)
        pq, fq = sim0.burst_sidelobes(w, c.astype(float) - sim0.MID, fs, fc, T)
        tb[w] = dict(psl_ideal_db=pi, psl_8bit_db=pq, floor_ideal_db=fi, floor_8bit_db=fq)
    M["tone_burst_300k_500us"] = tb

    # 5. per-waveform: matched-filter PSLR, out-of-band level, 8-bit floor, first image
    wf = {}
    for k, (x, c, meta) in reg.items():
        ac = c.astype(float) - sim0.MID
        f, d = sim0.esd_db(ac, fs, nfft=1 << 18)
        fi_, di = sim0.esd_db(sim0.AMP * x, fs, nfft=1 << 18)
        fl = (f >= 1.5e6) & (f <= 0.9 * fs / 2)
        wf[k] = dict(
            pslr_matched_filter_db=sim0.autocorr_pslr_db(ac, fs, meta),  # on the 8-bit codes
            level_at_600kHz_db=float(np.interp(600e3, f, d)),
            floor_1p5M_up_8bit_db=float(10 * np.log10(np.mean(10 ** (d[fl] / 10)))),
            floor_1p5M_up_ideal_db=float(10 * np.log10(np.mean(10 ** (di[fl] / 10)))),
            first_image_db_butter=sim0.image_levels(c, fs, "butter"),
            first_image_db_raw=sim0.image_levels(c, fs, "none"),
        )
    M["waveforms"] = wf

    # 6. ZOH droop + filter, for 10 and 5 MS/s
    zf = {}
    for r in (sim0.FS, sim0.FS_FALLBACK):
        img = r - sim0.BAND[1]
        zf[f"{r / 1e6:g}MS/s"] = dict(
            zoh_droop_100k_db=float(sim0.zoh_db(100e3, r)),
            zoh_droop_500k_db=float(sim0.zoh_db(500e3, r)),
            image_freq_hz=img,
            zoh_image_rel_500k_db=float(sim0.zoh_db(img, r) - sim0.zoh_db(500e3, r)),
            butter_atten_image_db=float(20 * np.log10(abs(sim0.filter_response(img, "butter")))),
            equal_atten_image_db=float(20 * np.log10(abs(sim0.filter_response(img, "equal")))),
        )
        z = zf[f"{r / 1e6:g}MS/s"]
        z["total_image_rejection_butter_db"] = z["zoh_image_rel_500k_db"] + z["butter_atten_image_db"] \
            - float(20 * np.log10(abs(sim0.filter_response(500e3, "butter"))))
    M["zoh_filter"] = zf
    M["filter_passband_db"] = {kind: {f"{int(f / 1e3)}k": float(20 * np.log10(abs(sim0.filter_response(f, kind))))
                                      for f in (100e3, 200e3, 350e3, 500e3)}
                               for kind in ("butter", "equal")}
    return M


# ---- figures ------------------------------------------------------------------
def pad_ac(codes, fs, pre=20e-6, post=40e-6):
    c = np.concatenate([np.full(int(pre * fs), sim0.MID), codes, np.full(int(post * fs), sim0.MID)])
    return np.arange(len(c)) / fs - pre, c


def fig_waveforms(reg, fs, out):
    fig, ax = plt.subplots(3, 2, figsize=(13, 8), gridspec_kw={"width_ratios": [2.2, 1]})
    for i, (name, ttl) in enumerate((("lfm_hann", "LFM chirp 100→500 kHz"),
                                     ("geo_hann", "Geometric sweep 100→500 kHz"),
                                     ("barker13_hann", "Phase-coded: Barker-13 BPSK on 250 kHz"))):
        x, c, meta = reg[name]
        t, cc = pad_ac(c, fs)
        w = sim0.window("hann", len(c))
        a = ax[i, 0]
        a.step(t * 1e6, cc, where="post", color=C[0], lw=0.5)
        for sgn in (1, -1):
            a.plot(np.arange(len(c)) / fs * 1e6, sim0.MID + sgn * sim0.AMP * w, color=C[1], lw=1.2, ls="--",
                   label="Hann envelope" if sgn == 1 else None)
        a.set(ylim=(-5, 260), ylabel="DAC code (0–255)", title=f"{ttl} — Hann window, 8-bit codes")
        a.axhline(128, color=MUTED, lw=0.6)
        a.legend(loc="upper right")
        # zoom where the frequency is highest-ish
        a = ax[i, 1]
        t0 = meta["T"] * 0.75
        s = int(t0 * fs)
        seg = c[s:s + int(12e-6 * fs)]
        a.step((np.arange(len(seg)) / fs + t0) * 1e6, seg, where="post", color=C[0], lw=1)
        a.plot((np.arange(len(seg)) / fs + t0) * 1e6, seg, ".", color=C[0], ms=3)
        a.set(ylabel="DAC code", title=f"Zoom 12 µs: stair-steps = ZOH ({fs / 1e6:g} MS/s)")
    for a in ax[-1]:
        a.set_xlabel("Time (µs)")
    fig.suptitle(f"Sim-0: the three modulation types as the R-2R DAC will see them (fs = {fs / 1e6:g} MS/s)",
                 fontweight="bold")
    fig.tight_layout()
    save(fig, os.path.join(out, "fig1_waveforms.png"))


def fig_mod_spectra(reg, fs, out):
    fig, ax = plt.subplots(1, 3, figsize=(15, 4.4), sharey=True)
    for a, (name, ttl) in zip(ax, (("lfm_hann", "LFM chirp 100→500 kHz"),
                                   ("geo_hann", "Geometric sweep 100→500 kHz"),
                                   ("barker13_hann", "Barker-13 BPSK, 250 kHz carrier"))):
        x, c, _ = reg[name]
        t, y, fa = sim0.analog(x * sim0.AMP + sim0.MID, fs)
        f, d = sim0.esd_db(y, fa, nfft=1 << 20)
        t, yq, fa = sim0.analog(c, fs)
        fq, dq = sim0.esd_db(yq, fa, nfft=1 << 20)
        s = f <= 1.5e6
        band(a)
        a.plot(fq[s] / 1e3, dq[s], color=C[0], lw=0.9, label="8-bit + ZOH + 3rd-order filter")
        a.plot(f[s] / 1e3, d[s], color=C[1], lw=0.9, ls="--", label="ideal (unquantised) + ZOH + filter")
        a.set(title=ttl, xlabel="Frequency (kHz)", ylim=(-110, 5))
        a.legend(loc="upper right")
    ax[0].set_ylabel("Energy spectral density (dB rel. peak)")
    fig.suptitle("Predicted output spectrum of each modulation type (Hann window, 500 µs / 416 µs pulses)",
                 fontweight="bold")
    fig.tight_layout()
    save(fig, os.path.join(out, "fig2_modulation_spectra.png"))


def fig_spectrograms(reg, fs, out):
    names = [f"lfm_c{int(f / 1e3)}k_hann" for f in sim0.CENTRES] + ["lfm_hann", "geo_hann", "barker13_hann"]
    titles = [f"LFM centred {int(f / 1e3)} kHz (±10%)" for f in sim0.CENTRES] + \
             ["LFM 100→500 kHz", "Geometric 100→500 kHz", "Barker-13 BPSK @ 250 kHz"]
    fig, ax = plt.subplots(2, 4, figsize=(16, 7.5))
    for a, name, ttl in zip(ax.flat, names, titles):
        x, c, meta = reg[name]
        t, cc = pad_ac(c, fs)
        f, tt, S = signal.spectrogram(cc.astype(float) - sim0.MID, fs, window="hann",
                                      nperseg=256, noverlap=240, mode="psd")
        S = 10 * np.log10(S / S.max() + 1e-12)
        m = f <= 800e3
        im = a.pcolormesh((tt + t[0]) * 1e6, f[m] / 1e3, S[m], vmin=-70, vmax=0, cmap="Blues",
                          shading="auto", rasterized=True)
        for b in sim0.BAND:
            a.axhline(b / 1e3, color=C[1], lw=0.8, ls="--")
        a.set(title=ttl, xlabel="Time (µs)", ylabel="Frequency (kHz)")
    ax.flat[-1].axis("off")
    ax.flat[-1].text(0.02, 0.6, "Dashed orange lines: 100 kHz and 500 kHz\nband edges.\n\n"
                     "8-bit codes, Hann window, fs = %g MS/s.\nSTFT: 256-pt Hann, 25.6 µs segments.\n"
                     "Colour: dB relative to panel peak." % (fs / 1e6), fontsize=10, color=INK2,
                     transform=ax.flat[-1].transAxes, va="top")
    fig.colorbar(im, ax=ax.flat[-1], location="bottom", fraction=0.08, label="dB")
    fig.suptitle("Predicted spectrograms: chirps at 100 / 200 / 350 / 500 kHz and the three modulation types",
                 fontweight="bold")
    fig.tight_layout()
    save(fig, os.path.join(out, "fig3_spectrograms.png"))


def fig_windows(reg, fs, out, M):
    fig, ax = plt.subplots(1, 3, figsize=(16, 4.6))
    a = ax[0]
    band(a)
    for i, w in enumerate(("rect", "hann")):
        t, y, fa = sim0.analog(reg[f"lfm_{w}"][1], fs)
        f, d = sim0.esd_db(y, fa, nfft=1 << 20)
        s = f <= 1.2e6
        a.plot(f[s] / 1e3, d[s], color=C[i], lw=0.9, label={"rect": "Rectangular", "hann": "Hann"}[w])
    a.set(title="LFM 100→500 kHz: rectangular vs Hann", xlabel="Frequency (kHz)",
          ylabel="dB rel. peak", ylim=(-100, 5))
    legend_below(a, 3)

    a = ax[1]
    fc, T = 300e3, sim0.PULSE_T
    N = sim0.n_samples(T, fs)
    for i, w in enumerate(sim0.WINDOWS):
        c = sim0.quantise(np.sin(2 * np.pi * fc * np.arange(N) / fs) * sim0.window(w, N))
        f, d = sim0.esd_db(c.astype(float) - sim0.MID, fs, nfft=1 << 20, ref_band=(fc - 50e3, fc + 50e3))
        s = (f > fc - 60e3) & (f < fc + 60e3)
        psl = M["tone_burst_300k_500us"][w]["psl_8bit_db"]
        a.plot((f[s] - fc) / 1e3, d[s], color=C[i], lw=0.9, label=f"{w}  (peak sidelobe {psl:.1f} dB)")
    a.set(title="300 kHz tone burst, 500 µs, 8-bit: window sidelobes", xlabel="Offset from 300 kHz (kHz)",
          ylabel="dB rel. peak", ylim=(-110, 5))
    legend_below(a)

    a = ax[2]
    for i, w in enumerate(("rect", "hann")):
        x = reg[f"lfm_{w}"][1].astype(float) - sim0.MID
        n = len(x)
        r = signal.correlate(x, x, method="fft")
        env = np.abs(signal.hilbert(r))
        lag = (np.arange(len(r)) - (n - 1)) / fs * 1e6
        a.plot(lag, 20 * np.log10(env / env.max() + 1e-12), color=C[i], lw=0.9,
               label=f"{w}  (peak sidelobe {M['waveforms'][f'lfm_{w}']['pslr_matched_filter_db']:.1f} dB)")
    a.set(xlim=(-30, 30), ylim=(-80, 3), title="Matched-filter output (range sidelobes)",
          xlabel="Lag (µs)", ylabel="dB rel. peak")
    legend_below(a)
    fig.suptitle("What windowing buys (Demand #10): sidelobes with and without a window", fontweight="bold")
    fig.tight_layout()
    save(fig, os.path.join(out, "fig4_window_comparison.png"))


def fig_quant(fs, out, M):
    fig, ax = plt.subplots(1, 3, figsize=(16, 4.6))
    a = ax[0]
    fc, T = 300e3, sim0.PULSE_T
    N = sim0.n_samples(T, fs)
    s = np.sin(2 * np.pi * fc * np.arange(N) / fs) * sim0.window("blackman", N)
    for i, (sig, lab) in enumerate(((sim0.quantise(s).astype(float) - sim0.MID, "8-bit quantised"),
                                    (sim0.AMP * s, "ideal (float)"))):
        f, d = sim0.esd_db(sig, fs, nfft=1 << 20, ref_band=(fc - 50e3, fc + 50e3))
        m = f <= fs / 2
        a.plot(f[m] / 1e6, d[m], color=C[i], lw=0.5 if i == 0 else 1.0, label=lab)
    tb = M["tone_burst_300k_500us"]["blackman"]
    a.axhline(-58.1, color=INK2, lw=1, ls="--", label="Blackman peak sidelobe, −58 dB")
    a.axhline(tb["floor_8bit_db"], color=C[2], lw=1.4, ls="-",
              label=f"8-bit floor, mean {tb['floor_8bit_db']:.0f} dB")
    a.set(title="Blackman 300 kHz burst (500 µs): 8-bit floor vs sidelobes", xlabel="Frequency (MHz)",
          ylabel="dB rel. peak", ylim=(-160, 5))
    legend_below(a)

    a = ax[1]
    for i, (ft, N, lab) in enumerate(((331 * fs / 8192, 8192, "%.1f kHz tone, 8192-pt FFT (non-periodic error)" % (331 * fs / 8192 / 1e3)),
                                      (500e3, 8000, "500 kHz tone: error periodic → harmonic spurs"))):
        c = sim0.quantise(np.sin(2 * np.pi * ft / fs * np.arange(N))).astype(float) - sim0.MID
        p = np.abs(np.fft.rfft(c)) ** 2
        d = 10 * np.log10(p / p.max() + 1e-30)
        f = np.fft.rfftfreq(N, 1 / fs) / 1e6
        if i == 0:
            a.plot(f, d, color=C[0], lw=0.3, alpha=0.7, label=lab)
        else:
            keep = d > -120
            a.plot(f[keep], d[keep], "o", color=C[1], ms=5, label=lab)
    a.axhline(M["cw_8192_noncoherent"]["floor_per_bin_dbc"], color=C[2], lw=1.4,
              label=f"simulated mean floor {M['cw_8192_noncoherent']['floor_per_bin_dbc']:.1f} dB")
    a.axhline(-86, color=INK2, lw=1, ls="--", label="docs' claim: −86 dB")
    a.set(title="Continuous full-scale tone, rectangular FFT, 8-bit", xlabel="Frequency (MHz)",
          ylabel="dB rel. carrier (per bin)", ylim=(-140, 5))
    legend_below(a, 1)

    a = ax[2]
    sc = M["sqnr_vs_digital_scale_db"]
    xs = list(sc)
    a.bar(range(len(xs)), [sc[k] for k in xs], color=C[0], width=0.6)
    for i, k in enumerate(xs):
        a.text(i, sc[k] + 0.8, f"{sc[k]:.1f} dB\n(≈{(sc[k] - 1.76) / 6.02:.1f} bits)", ha="center", fontsize=8)
    a.set_xticks(range(len(xs)), [f"{float(k) * 100:g}%" for k in xs])
    a.set(ylim=(0, 60), title="SQNR if amplitude were scaled digitally",
          xlabel="Digital amplitude (fraction of full scale)", ylabel="SQNR (dB)")
    a.grid(axis="x", visible=False)
    fig.suptitle("8-bit quantisation: where the floor actually sits", fontweight="bold")
    fig.tight_layout()
    save(fig, os.path.join(out, "fig5_quantisation.png"))


def fig_zoh(reg, fs, out):
    fig, ax = plt.subplots(1, 2, figsize=(15, 4.8), gridspec_kw={"width_ratios": [1.6, 1]})
    c = reg["lfm_hann"][1]
    a = ax[0]
    t, y, fa = sim0.analog(c, fs, filt="none")
    f, d = sim0.esd_db(y, fa, nfft=1 << 20, ref_band=sim0.BAND)
    t, yf, fa = sim0.analog(c, fs, filt="butter")
    ff, df = sim0.esd_db(yf, fa, nfft=1 << 20, ref_band=sim0.BAND)
    m = f <= 3.2 * fs
    a.plot(f[m] / 1e6, d[m], color=C[1], lw=0.6, label="raw ladder output (ZOH images)")
    a.plot(ff[m] / 1e6, df[m], color=C[0], lw=0.6, label="after 3rd-order Butterworth, 700 kHz")
    fg = np.linspace(1e3, 3.2 * fs, 4000)
    a.plot(fg / 1e6, sim0.zoh_db(fg, fs), color=INK2, lw=1, ls="--", label="ZOH sinc envelope")
    a.plot(fg / 1e6, 20 * np.log10(np.abs(sim0.filter_response(fg))), color=C[2], lw=1, ls="--",
           label="filter response")
    for k in (1, 2, 3):
        a.axvline(k * fs / 1e6, color=MUTED, lw=0.6, ls=":")
    a.set(ylim=(-160, 5), xlabel="Frequency (MHz)", ylabel="dB rel. in-band peak",
          title=f"LFM 100→500 kHz (Hann): images at k·fs ± f, fs = {fs / 1e6:g} MS/s")
    a.legend(loc="upper right", fontsize=8)

    a = ax[1]
    fg = np.linspace(1e3, 1.2e6, 1000)
    band(a)
    a.plot(fg / 1e3, sim0.zoh_db(fg, fs), color=INK2, ls="--", label=f"ZOH sinc ({fs / 1e6:g} MS/s)")
    a.plot(fg / 1e3, 20 * np.log10(np.abs(sim0.filter_response(fg, "butter"))), color=C[0],
           label="3rd-order Butterworth 700 kHz")
    a.plot(fg / 1e3, 20 * np.log10(np.abs(sim0.filter_response(fg, "equal"))), color=C[1],
           label="3 equal RC poles (1 kΩ / 220 pF)")
    a.plot(fg / 1e3, sim0.zoh_db(fg, fs) + 20 * np.log10(np.abs(sim0.filter_response(fg, "butter"))),
           color=C[2], lw=1.8, label="ZOH + Butterworth (total)")
    a.set(ylim=(-10, 1), xlabel="Frequency (kHz)", ylabel="Gain (dB)", title="Passband droop across the band")
    a.legend(loc="lower left", fontsize=8)
    fig.suptitle("Zero-order hold and reconstruction filter", fontweight="bold")
    fig.tight_layout()
    save(fig, os.path.join(out, "fig6_zoh_filter.png"))


# ---- synthetic "measured" data --------------------------------------------------
def synthetic_measured(codes, fs, out, seed=58):
    """Predicted chain + plausible non-idealities, sampled like a 50 MS/s 8-bit
    scope. Clearly SYNTHETIC: exercises `compare` before any hardware exists."""
    rng = np.random.default_rng(seed)
    pre, post = 100e-6, 150e-6
    c = np.concatenate([np.full(int(pre * fs), sim0.MID), codes, np.full(int(post * fs), sim0.MID)]).astype(np.uint8)
    bits = (c[:, None] >> np.arange(8)) & 1
    weights = 2.0 ** np.arange(8) * (1 + rng.normal(0, 0.004, 8))     # 0.4 % bit-weight error
    lad = bits @ weights
    up = 5                                                             # 50 MS/s scope
    t, v, fa = sim0.analog(lad, fs, up=up, fc=680e3, pre=0, post=0)   # filter 3 % low
    v = 1.2 * v                                                        # op-amp gain
    v = v + 8e-4 * v ** 2 + 5e-4 * v ** 3                              # ~-62 dBc HD2, ~-66 dBc HD3
    v = 2.5 + v + rng.normal(0, 2e-3, len(v))                         # mid-rail + 2 mV rms noise
    lsb = 4.0 / 256                                                    # scope: 8-bit, 0.5 V/div x 8 div
    v = np.round((v - 2.5) / lsb) * lsb + 2.5
    t = t - pre + 3.7e-6                                              # scope trigger 3.7 us early
    tpath = os.path.join(out, "synthetic_measured_lfm_hann_time.csv")
    np.savetxt(tpath, np.column_stack([t, v]), delimiter=",", fmt="%.9g",
               header="SYNTHETIC -- NOT A MEASUREMENT. Generated by run_all.py to test compare.py.\n"
                      "time_s,voltage_v", comments="# ")
    print("  wrote", tpath)
    # analyser-style spectrum export: 3 kHz RBW, 0-5 MHz, 4001 points, dBm-ish absolute offset
    f, d = sim0.esd_db(v - v.mean(), fa, nfft=1 << 21)
    rbw = 3e3
    k = int(round(rbw / (f[1] - f[0])))
    lin = np.convolve(10 ** (d / 10), np.ones(k) / k, mode="same")
    fg = np.linspace(0, 5e6, 4001)
    dg = 10 * np.log10(np.interp(fg, f, lin) + 10 ** (-85 / 10) * rng.exponential(1, fg.size)) - 7.0
    spath = os.path.join(out, "synthetic_measured_lfm_hann_spectrum.csv")
    np.savetxt(spath, np.column_stack([fg, dg]), delimiter=",", fmt="%.6g",
               header="SYNTHETIC -- NOT A MEASUREMENT. Emulated analyser, RBW 3 kHz.\nfrequency_hz,level_dbm",
               comments="# ")
    print("  wrote", spath)
    return tpath, spath


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fs", type=float, default=sim0.FS)
    a = ap.parse_args()
    fs = a.fs
    out = os.path.join(HERE, "out") if fs == sim0.FS else os.path.join(HERE, "out", f"fs{fs / 1e6:g}M")
    os.makedirs(out, exist_ok=True)
    print(f"Sim-0 at fs = {fs / 1e6:g} MS/s -> {out}")
    reg = sim0.table_registry(fs)
    write_headers(reg, fs, out)
    M = metrics(reg, fs)
    fig_waveforms(reg, fs, out)
    fig_mod_spectra(reg, fs, out)
    fig_spectrograms(reg, fs, out)
    fig_windows(reg, fs, out, M)
    fig_quant(fs, out, M)
    fig_zoh(reg, fs, out)
    tpath, spath = synthetic_measured(reg["lfm_hann"][1], fs, out)
    M["synthetic_compare_time"] = compare(tpath, "lfm_hann", fs, out=out)
    M["synthetic_compare_spectrum"] = compare(spath, "lfm_hann", fs, rbw=3e3, out=out)
    with open(os.path.join(out, "metrics.json"), "w") as fh:
        json.dump(M, fh, indent=1, default=float)
    print("  wrote", os.path.join(out, "metrics.json"))
    summary(M)


def summary(M):
    print("\n=== key numbers ===")
    print(f"theory SQNR full-scale sine: {M['sqnr_theory_fullscale_sine_db']:.2f} dB")
    for k in M["waveforms"]:
        w = M["waveforms"][k]
        pslr = w['pslr_matched_filter_db']
        pslr = "  mono" if pslr is None else f"{pslr:6.1f}"
        print(f"{k:16s} SQNR {M['sqnr_db'][k]:6.2f} dB | PSLR {pslr} | "
              f"600k {w['level_at_600kHz_db']:6.1f} | floor 8b {w['floor_1p5M_up_8bit_db']:6.1f} "
              f"ideal {w['floor_1p5M_up_ideal_db']:7.1f} | image {w['first_image_db_butter']:6.1f} raw {w['first_image_db_raw']:5.1f}")
    print("window PSL:", {k: round(v, 2) for k, v in M["window_psl_db"].items()})
    for w, v in M["tone_burst_300k_500us"].items():
        print(f"burst {w:9s}", {k: round(x, 1) for k, x in v.items()})
    print("CW 8192:", M["cw_8192_noncoherent"])
    print("CW exact:", M["cw_exact_ratio_tones"])
    print("digital scale SQNR:", M["sqnr_vs_digital_scale_db"])
    print("ZOH/filter:", json.dumps(M["zoh_filter"], indent=1))
    print("passband:", M["filter_passband_db"])
    for k in ("synthetic_compare_time", "synthetic_compare_spectrum"):
        print(k, {a: b for a, b in M[k].items() if a not in ("png", "csv", "file")})


if __name__ == "__main__":
    main()
